# Generated by Django 3.2.16 on 2024-01-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_auto_20240103_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
